import { ROLES, type UserRole } from './roles'

export const PERMISSION_MODULES = {
  USERS: 'users',
  ACCOUNTING: 'accounting',
  RESERVATIONS: 'reservations',
  CONTACTS: 'contacts',
  LOGS: 'logs',
  SETTINGS: 'settings',
  EMAIL: 'email',
} as const

export type PermissionModule = (typeof PERMISSION_MODULES)[keyof typeof PERMISSION_MODULES]

export const PERMISSIONS = {
  [PERMISSION_MODULES.USERS]: [ROLES.ADMIN, ROLES.ACCOUNTANT],
  [PERMISSION_MODULES.ACCOUNTING]: [ROLES.ADMIN, ROLES.ACCOUNTANT],
  [PERMISSION_MODULES.RESERVATIONS]: [ROLES.ADMIN, ROLES.ACCOUNTANT, ROLES.FRONT_DESK],
  [PERMISSION_MODULES.CONTACTS]: [ROLES.ADMIN, ROLES.ACCOUNTANT, ROLES.FRONT_DESK],
  [PERMISSION_MODULES.LOGS]: [ROLES.ADMIN, ROLES.ACCOUNTANT],
  [PERMISSION_MODULES.SETTINGS]: [ROLES.ADMIN, ROLES.ACCOUNTANT],
  [PERMISSION_MODULES.EMAIL]: [ROLES.ADMIN, ROLES.ACCOUNTANT, ROLES.FRONT_DESK],
} as const satisfies Record<PermissionModule, readonly UserRole[]>
