// Generates src/generated/db-meta.ts from prisma/schema.prisma.
// Records, per model, which DateTime fields are date-only (@db.Date) or
// time-only (@db.Time) and which fields are relations, so rows returned by
// Prisma can be serialized back to the JSON shape the app uses
// (YYYY-MM-DD dates, HH:MM:SS times, ISO timestamps, numbers for decimals).
import fs from 'node:fs'
import path from 'node:path'

const root = path.resolve(import.meta.dirname, '..')
const schema = fs.readFileSync(path.join(root, 'prisma/schema.prisma'), 'utf8')

const models = {}
for (const [, name, body] of schema.matchAll(/^model (\w+) \{([\s\S]*?)^\}/gm)) {
  const meta = { dateFields: [], timeFields: [], timestampFields: [], relations: {} }
  const modelNames = new Set([...schema.matchAll(/^model (\w+) \{/gm)].map((m) => m[1]))
  for (const line of body.split('\n')) {
    const m = line.trim().match(/^(\w+)\s+(\w+)(\[\])?\??(\s|$)/)
    if (!m || line.trim().startsWith('@@')) continue
    const [, field, type] = m
    if (type === 'DateTime' && /@db\.Date\b/.test(line)) meta.dateFields.push(field)
    if (type === 'DateTime' && /@db\.Time\b/.test(line)) meta.timeFields.push(field)
    if (type === 'DateTime' && /@db\.Timestamptz\b/.test(line)) meta.timestampFields.push(field)
    if (modelNames.has(type)) meta.relations[field] = type
  }
  models[name] = meta
}

const out = `// Generated by scripts/gen-db-meta.mjs — do not edit.
export const DB_META = ${JSON.stringify(models, null, 2)} as const satisfies Record<string, { dateFields: readonly string[]; timeFields: readonly string[]; timestampFields: readonly string[]; relations: Record<string, string> }>

export type DbModelName = keyof typeof DB_META
`
fs.mkdirSync(path.join(root, 'src/generated'), { recursive: true })
fs.writeFileSync(path.join(root, 'src/generated/db-meta.ts'), out)
console.log(`db-meta: ${Object.keys(models).length} models`)
